name: Deploy to Github Pages

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - ".github/**"
      - ".vscode/**"
      - ".gitignore"
      - "LICENSE"
      - "README.md"
  pull_request:
    branches:
      - master
    paths-ignore:
      - ".github/**"
      - ".vscode/**"
      - ".gitignore"
      - "LICENSE"
      - "README.md"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "^1.21.0"
      - run: go version

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "latest"
          extended: true

      - name: Build
        run: |
          hugo --minify --gc
          hugo --minify --gc --baseURL "https://www.wegod.cc/" --destination public_wegod.cc


      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: public
          clean: true
          single-commit: true

      - name: Deploy wegod.cc
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: wegod.cc
          folder: public_wegod.cc
          clean: true
          single-commit: true
