name: Deploy to Github Pages

on:
  push:
    branches:
      - master
    paths-ignore:
      - ".github/**"
      - ".vscode/**"
      - ".gitignore"
      - "LICENSE"
      - "README.md"
  pull_request:
    branches:
      - master
    paths-ignore:
      - ".github/**"
      - ".vscode/**"
      - ".gitignore"
      - "LICENSE"
      - "README.md"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: "^1.20.0"
      - run: go version

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"
          extended: true

      - name: Build
        run: hugo --minify --gc

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: public
          clean: true
          single-commit: true
